extends Object

const CREATE_PLAYER_REQUEST = 1
const CREATE_PLAYER_RESPONSE = 2
const PING_REQUEST = 3
const PING_RESPONSE = 4
const GET_ROOM_LIST_REQUEST = 5
const GET_ROOM_LIST_RESPONSE = 6
const JOIN_ROOM_REQUEST = 7
const JOIN_ROOM_RESPONSE = 8
const PLAYER_LOGIN_REQUEST = 9
const PLAYER_LOGIN_RESPONSE = 10
const GET_PLAYER_LIST_REQUEST = 11
const GET_PLAYER_LIST_RESPONSE = 12
const INPUT_STATE_REQUEST = 13
const INPUT_STATE_RESPONSE = 14
const PLAYER_POSITION_PUSH = 15