extends Object

const CREATE_ROOM_REQUEST = 1;
const CREATE_ROOM_RESPONSE = 2;
const JOIN_ROOM_REQUEST = 3;
const JOIN_ROOM_RESPONSE = 4;
const CREATE_PLAYER_REQUEST = 5;
const CREATE_PLAYER_RESPONSE = 6;
const INPUT_STATE_REQUEST = 7;
const INPUT_STATE_RESPONSE = 8;
const PLAYER_POSITION_REQUEST = 9;