extends Object

const PING_REQUEST = 1;
const PING_RESPONSE = 2;

const CREATE_PLAYER_REQUEST = 3;
const CREATE_PLAYER_RESPONSE = 4;

const PLAYER_LOGIN_REQUEST = 5;
const PLAYER_LOGIN_RESPONSE = 6;

const GET_ROOM_LIST_REQUEST = 7;
const GET_ROOM_LIST_RESPONSE = 8;

const JOIN_ROOM_REQUEST = 9;
const JOIN_ROOM_RESPONSE = 10;

const START_GAME_REQUEST = 11;
const START_GAME_RESPONSE = 12;

const GET_PLAYER_LIST_REQUEST = 13;
const GET_PLAYER_LIST_RESPONSE = 14;

const INPUT_STATE_REQUEST = 15;
const INPUT_STATE_RESPONSE = 16;

const PLAYER_POSITION_PUSH = 17;